HW7
Arden30/TinkoffJavaBackend23-24 pull request #10
Opened 2023-11-24 14:42 UTC by Arden30

2023-12-05 20:53 UTC, snitron requested changes
В целом, очень неплохая работа. 
Можешь поправить замечания (minor править необязательно, это скорее рекомендации), тогда поставлю максимум (с 3ей таской самые большие вопросы). Также, если есть вопросы/не согласен с комментариями, можешь пинговать меня в телегу или писать тут в комментах.

2/3

2023-12-05 20:53 UTC, snitron commented on src/main/java/edu/hw7/task2/ParallelFactorial.java
> +        return IntStream.rangeClosed(1, n).parallel().reduce((x, y) -> x * y).orElse(1);
``Integer``, конечно, может быть маловато для факториала) но идея верная, так что норм

2023-12-05 20:53 UTC, snitron commented on src/main/java/edu/hw7/task3_and_3_5/FinderService.java
> +        database.put(person.id(), person);
Что будет, если придёт ``person`` с ``id``, который есть в базе, но другими остальными данными? Кажется, это приведёт к неконсистентости базы и твоих быстрых кэшей (хэшмап). 

Плюс не совсем понятно, зачем они вообще нужны? При поиске ты всё равно за линию итерируешься по ним, так почему бы не итерироваться по ``database``? И не тратить лишнюю память

2023-12-05 20:53 UTC, snitron commented on src/main/java/edu/hw7/task3_and_3_5/ReadWriteLockFinderService.java
> +public class ReadWriteLockFinderService implements PersonDataBase {
Вопросы такие же, как и для синхронизированной версии

2023-12-05 20:53 UTC, snitron commented on src/main/java/edu/hw7/task4/MonteCarloMultithreading.java
> +        while (totalCount++ < n) {
minor: почему не for?

2023-12-10 17:23 UTC, Arden30 commented
@snitron пофиксил. 
Посмотрите, пожалуйста, предыдущее дз 6 и 3 проект, а то их как будто пропустили)

2023-12-13 00:11 UTC, snitron approved these changes
Верю, что ``writeLock()`` не специально, но надо быть внимательнее) Поставил

3/3

2023-12-13 00:11 UTC, snitron commented on src/main/java/edu/hw7/task3_and_3_5/ReadWriteLockFinderService.java
> +        lock.writeLock().lock();
rly?)

2023-12-13 00:12 UTC, snitron commented
> @snitron пофиксил. Посмотрите, пожалуйста, предыдущее дз 6 и 3 проект, а то их как будто пропустили)

Посмотрю обязательно ASAP👌

2023-12-13 16:51 UTC, merged