HW6
Arden30/TinkoffJavaBackend23-24 pull request #8
Opened 2023-11-17 15:27 UTC by Arden30

2023-12-13 00:26 UTC, snitron requested changes
Работа ОК, но с недочётами. Пока ставлю 2/3

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    private final Path path = Path.of("src/test/java/edu/hw6/task1/disk.txt");
Почему хардкод?

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            for (String key : disk.keySet()) {
Можно юзать ``.entrySet()`` и дополнительно не делать ``.get()``

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            throw new RuntimeException();
Лучше сказать пользователю, что пошло не так.
И почему RE? Почему бы не сделать функцию ``throws IOException``?

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task1/DiskMap.java
> +                String[] arr = str.split(":");
minor: а там точно внутри ровно 2 элемента, в массиве?

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task2/FileCloner.java
> +            String extension = "." + file.split(PATTERN)[1];
Правильно ли отработает для ``my-best-archive.tar.gz``?

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task3/MagicNumberFilter.java
> +            byte[] bytes = Files.readAllBytes(path);
Вычитать весь файл, чтобы проверить некоторое число магических байт (при больщом размере файла, что вполне может быть) --- звучит странно

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task3/GlobFilter.java
> +    static AbstractFilter globMatches(String extension) {
minor: @NotNull

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task5/HackerNews.java
> +            return "Title was not found";
Это нестандартная ситуация, лучше кидать Exception

Либо null + обозначить это в контракте функции (если не знаешь про контракты, https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5), в этом случае просто в комменте написать

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task6/PortScanner.java
> +                if (PORTS.containsKey(port)) {
Два раза ходишь в мапу, можно ``getOrDefault``, или ``null`` и сравнить на ``null`` потом

2023-12-13 00:26 UTC, snitron commented on src/main/java/edu/hw6/task6/PortScanner.java
> +            } else if (scanUDP(port)) {
А одновременно не могут быть TCP и UDP на этом порту?

2023-12-13 00:26 UTC, snitron commented on src/test/java/edu/hw6/task1/Task1Test.java
> +        diskMap.put("hi", "java");
:sunglasses:

2023-12-13 16:51 UTC, merged

2023-12-17 11:04 UTC, Arden30 commented
@snitron 
Фиксы здесь: https://github.com/Arden30/TinkoffJavaBackend23-24/pull/17